name: docker_image

on:
  workflow_run:
    workflows:
      - publish
    types:
      - completed

jobs:
  build_docker_images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # We assume the form of tag names are like 1.2.3 (semantic versioning).
      - name: Git Tag name
        id: vars
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag=$(gh release view --json tagName --jq .tagName)
          echo "::set-output name=tag::${tag##v}"

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: zulu

      # docker image
      - name: Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build pochi3
        run: ./gradlew build

      - name: Build and Push Docker Images with jib
        run: |
          curl -LO https://github.com/GoogleContainerTools/jib/releases/download/v0.10.0-cli/jib-jre-0.10.0.zip
          unzip jib-jre-0.10.0.zip
          EPOCH=$(date +%s)

          ./jib-0.10.0/bin/jib build --build-file ./dockers/jib.yaml \
            --to-password "${{ secrets.GITHUB_TOKEN }}" \
            --to-username tamada \
            --target="ghcr.io/tamada/pochi3:${{ steps.vars.outputs.tag }}-distroless" \
            --additional-tags=${{ steps.vars.outputs.tag }},distroless,latest \
            --verbosity=debug \
            --parameter=VERSION=${{ steps.vars.outputs.tag }} \
            --parameter=BASE_IMAGE=gcr.io/distroless/java17-debian11 \
            --parameter=CURRENT_EPOCH=${EPOCH}

          ./jib-0.10.0/bin/jib build --build-file ./dockers/jib.yaml \
            --to-password "${{ secrets.GITHUB_TOKEN }}" \
            --to-username tamada \
            --target="ghcr.io/tamada/pochi3:${{ steps.vars.outputs.tag }}-fullgrl" \
            --additional-tags=fullgrl \
            --verbosity=debug \
            --parameter=VERSION=${{ steps.vars.outputs.tag }} \
            --parameter=BASE_IMAGE=ghcr.io/graalvm/jdk:ol8-java17-22.1.0 \
            --parameter=CURRENT_EPOCH=${EPOCH}

      - name: Build and Push Docker Images of Minimal GraalVM
        uses: docker/build-push-action@v3
        with:
          push: true
          file: dockers/minimalgrl/Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/tamada/pochi3:${{ steps.vars.outputs.tag }}-minimalgrl
            ghcr.io/tamada/pochi3:minimalgrl

      - name: Build and Push Docker Images of Minimal JRE
        uses: docker/build-push-action@v3
        with:
          push: true
          file: dockers/minimaljre/Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/tamada/pochi3:${{ steps.vars.outputs.tag }}-minimaljre
            ghcr.io/tamada/pochi3:minimaljre
