name: update_version
on:
  push:
    branches:
      - release/v*

jobs:
  update_version:
    runs-on: ubuntu-latest
    steps:
      - name: Git Tag Name
        id: vars
        run: |
          echo "::set-output name=branch::${GITHUB_REF#refs/heads/}"
          echo "::set-output name=tag::${GITHUB_REF##**/v}"

      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ steps.vars.outputs.branch }}
          fetch-depth: 0

      - name: Initialize Git
        run: |
          git config --global user.name  "GitHub Actions"
          git config --global user.email "action@github.com"
          auth_header="$(git config --local --get http.https://github.com/.extraheader)"
          git worktree add site/public gh-pages

      - name: Update version
        run: |
          sed 's/${VERSION}/${{ steps.vars.outputs.tag }}/g' templates/README.md > README.md
          echo 'v${{ steps.vars.outputs.tag }}' > site/layouts/shortcodes/version.html 
          sed "s/version = \'.*\'/version = \'${{ steps.vars.outputs.tag }}\'/g" buildSrc/src/main/groovy/pochi.java-conventions.gradle > a
          mv a buildSrc/src/main/groovy/pochi.java-conventions.gradle
          sed 's/${VERSION}/${{ steps.vars.outputs.tag }}/g' templates/VersionProvider.java > pochi-cli/src/main/java/jp/cafebabe/pochi/cli/VersionProvider.java
          git commit -a -m "update version to ${{ steps.vars.outputs.tag }}, ready to publish v${{ steps.vars.outputs.tag }}" || true

      - name: Push branch
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ steps.vars.outputs.branch }}

      - name: Create pull request
        uses: peter-evans/create-pull-request@v4
        with:
          branch: ${{ steps.vars.outputs.branch }}
          title: ${{ steps.vars.outputs.branch }}
